# Generated by Django 2.0.5 on 2018-05-22 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(unique=True, verbose_name='题目')),
                ('pic', models.ImageField(blank=True, upload_to='imgfiles', verbose_name='图片')),
                ('rightanswer', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=2, verbose_name='答案')),
                ('detail', models.TextField(blank=True, verbose_name='解答')),
                ('creattime', models.DateTimeField(auto_now_add=True)),
                ('bodyselect', models.CharField(choices=[('selected', '已选定'), ('deselect', '未选定')], default='deselect', max_length=8, verbose_name='选定')),
                ('bssort', models.IntegerField(blank=True, default=1, verbose_name='题目次序')),
            ],
        ),
        migrations.CreateModel(
            name='Cresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=8, verbose_name='学生姓名')),
                ('answer', models.CharField(max_length=2, verbose_name='学生回答')),
                ('answerdetail', models.CharField(blank=True, max_length=256, verbose_name='理由')),
                ('answerstate', models.NullBooleanField()),
                ('answertime', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choic.Choices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='choices',
            name='tag',
            field=models.ManyToManyField(to='choic.Tag'),
        ),
    ]
